### ISSUE TITLE
Spanish Translation - ES

### ISSUE THREAD

**Issue by Neoazureus** [zsnmwy/ONI-geyser-calculator#11]
Language Name: Spanish - Español
Country: Spain - España

I have little knowledge in programming, so I better leave this here
English subtitle is good, the reference to the game is better understood in its original language, but I translated it

         //Refer to the EN online page

        title: 'Calculadora de géiseres ONI (Vista previa)',
        sub_title: 'Buen géiser no incluido',
        issue: 'Problema',
        how_is_it_work: '¿Cómo funciona?',

        fill_geyser_info: 'Rellene la información del géiser',
        Geyser_Information: 'Información del géiser',
        Please_fill_the_geyser_information: 'Por favor, rellene la información del géiser.',
        and_click_cal: 'Y clicar en "Calcular".',
        cal: 'Calcular',
        better_than: 'Mejor que el ${0}% del mismo tipo de géiser.',
        average_daily_output: 'Promedio real de producción por segundo : ${0} kg/s',

        RT_Eruption: 'Tasa de erupción',
        Eruption_Period: 'Periodo de erupción',
        Acitve_Period: 'Periodo activo', //original var acitve_period
        g: 'g',
        s: 's',
        cycle: 'ciclos',
        per: ' ', // there is not this string in the game, but you can use 'para'
        every: 'cada',

        Cool_Steam_Vent: 'Fumarola de vapor fresco',
        Steam_Vent: 'Fumarola de vapor',
        Water_Geyser: 'Géiser de agua',
        Cool_Slush_Geyser: 'Géiser de aguanieve fresca',
        Polluted_Water_Vent: 'Fumarola de agua contaminada',
        Minor_Volcano: 'Volcán menor',
        Volcano: 'Volcán',
        Carbon_Dioxide_Geyser: 'Géiser de dióxido de carbono',
        Carbon_Dioxide_Vent: 'Fumarola de dióxido de carbono',
        Hydrogen_Vent: 'Fumarola de Hidrógeno',
        Polluted_Oxygen_Vent: 'Fumarola de oxígeno contaminado',
        Infectious_Polluted_Oxygen_Vent: 'Fumarola de oxígeno contaminado infeccioso',
        Chlorine_Gas_Vent: 'Fumarola de gas cloro',
        Natural_Gas_Geyser: 'Geíser de gas natural',
        Copper_Volcano: 'Volcán de cobre',
        Iron_Volcano: 'Volcán de hierro',
        Gold_Volcano: 'Volcán de oro',
        Leaky_Oil_Fissure: 'Fisura con fugas de crudo',

        or: 'o',
        click_here: 'clicar aquí',
        to_upload_your_cap: 'Para subir su captura de pantalla del géiser.',
        finish_recognition: 'El reconocimiento está completo. el resultado del reconocimiento puede ser incorrecto. Por favor verifiquelo y haga clic en "Calcular"',
        reupload: 'Volver a subir',
        image_too_large: 'El tamaño de la imagen es demasiado grande.',

**Comment by zsnmwy** [comment]
Thanks for your translation.

And I'm add Spanish in a temporary web site just now.

https://zsnmwy.coding.me/ONI-PR/

Please check it.

The web site language will auto jump to your local browser language in normal.

---

I will add a new message in the web site.

Please taanslate it .

```
Store: ${0}kg/tile, ${1} tiles/cycle
```

Thanks.

**Comment by Neoazureus** [comment]
`Store: ${0}kg/tile, ${1} tiles/cycle`

`Almacén: ${0}kg/bloque, ${1} bloque/ciclo`

I'm finishing the French translation. I'll check the Spanish page later.
I have made some changes in the Spanish translation, you can replace the code again.

**Comment by zsnmwy** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5aee5640c9b0cf0e008c3273/attachments/5af5855bc9b0cf0e008deab6)


Please check the temporary web site.

https://zsnmwy.coding.me/ONI-PR/

Please use `Ctrl` + `F5` to refresh the page.

**Comment by Neoazureus** [comment]
Please change this line

`Almacén: ${0}kg/bloque, ${1} bloques/ciclo`
and
`Minor_Volcano: 'Volcán menor',`

And I do not know why this character appears wrong on the page "¿"

It appears:
![image](https://user-images.githubusercontent.com/39187234/39948360-413f76e8-553b-11e8-9c3b-17b314d66b69.png)

If it don't work, you can change this line:

`how_is_it_work: '¿Cómo funciona?',` for
`how_is_it_work: 'Cómo funciona?',`

**Comment by zsnmwy** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5aee5640c9b0cf0e008c3273/attachments/5af630d8c9b0cf0e008e0be9)

![image](https://app.gitkraken.com/api/glo/boards/5aee5640c9b0cf0e008c3273/attachments/5af6316d4f33b71500166ef2)


Please check the temporary web site.

https://zsnmwy.coding.me/ONI-PR/

Please use `Ctrl` + `F5` to refresh the page.

**Comment by Neoazureus** [comment]
It's ok

**Comment by zsnmwy** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5aee5640c9b0cf0e008c3273/attachments/5afaf7504f33b71500174fab)

The web site update is OK.

Please use `Ctrl` + `F5` to refresh the page.
