### ISSUE TITLE
French Translation - FR

### ISSUE THREAD

**Issue by Neoazureus** [zsnmwy/ONI-geyser-calculator#12]
Language Name: French - Français
Country: France - France

There are  \' characters in French language, so i use this character escape, and i comment it with char_esc. If i'm wrong, please change it.

        title: 'Calculatrice de Geysers (Aperçu)',
        sub_title: 'Bon geyser non inclus',
        issue: 'Problème',
        how_is_it_work: 'Comment ça marche ?',

        fill_geyser_info: 'Remplissez les informations du geyser',
        Geyser_Information: 'Informations du geyser',
        Please_fill_the_geyser_information: 'Veuillez remplir les informations du geyser.',
        and_click_cal: 'Et cliquez sur "Calculer".',
        cal: 'Calculer',
        better_than: 'Mieux que le ${0}% du même type de geyser.',
        average_daily_output: 'Moyenne réelle de production par seconde : ${0} kg/s',

        RT_Eruption: 'Taux d\'eruption', //character escape (?) please change if i'm wrong
        Eruption_Period: 'Période d\'éruption', // char_esc
        Acitve_Period: 'Période d\'activité', //original var acitve, char_esc
        g: 'g',
        s: 's',
        cycle: 'cycles',
        per: ' ', // there is not this string in the game, but you can use 'pour'
        every: 'tous les',

        Cool_Steam_Vent: 'Fumerolle de vapeur fraîche',
        Steam_Vent: 'Fumerolle de vapeur',
        Water_Geyser: 'Geyser d\'eau', // char_esc
        Cool_Slush_Geyser: 'Geyser de neige fondue froide',
        Polluted_Water_Vent: 'Fumerolle d\'eau polluée', //char_esc
        Minor_Volcano: 'Volcan mineur',
        Volcano: 'Volcan',
        Carbon_Dioxide_Geyser: 'Geyser de dioxyde de carbone',
        Carbon_Dioxide_Vent: 'Fumerolle de dioxyde de carbone',
        Hydrogen_Vent: 'Fumerolle d\'hydrogène', //char_esc
        Polluted_Oxygen_Vent: 'Fumerolle d\'oxygène pollué', //char_esc
        Infectious_Polluted_Oxygen_Vent: 'Fumerolle d\'oxygène pollué infectieux', //char_esc
        Chlorine_Gas_Vent: 'Fumerolle de chlore gazeux',
        Natural_Gas_Geyser: 'Geyser de gaz naturel',
        Copper_Volcano: 'Volcan de cuivre',
        Iron_Volcano: 'Volcan de fer',
        Gold_Volcano: 'Volcan d\'or', //char_esc
        Leaky_Oil_Fissure: 'Fissure de pétrole brut',

        or: 'ou',
        click_here: 'cliquez ici',
        to_upload_your_cap: 'Pour télécharger votre capture d\'écran du geyser.', //char_esc
        finish_recognition: 'La reconnaissance est terminée. le résultat de la reconnaissance peut être incorrect. Veuillez vérifier et cliquer sur "Calculer"',
        reupload: 'Télécharger à nouveau',
        image_too_large: 'La taille de l\'image est trop grande.', //char_esc`

**Comment by mutoe** [comment]
`'Taux d\'eruption'` This usage is correct.
You can also wrap strings in double quotes to make statements more readable. Like this
``` js
Water_Geyser: "Geyser d'eau",
```
(In Javascript, strings can be wrapped in single or double quotes, and the effect is the same.)

**Comment by Neoazureus** [comment]
oh, thx. I only have basic (or less) knowledge of Visual Basic, python and C#

**Comment by zsnmwy** [comment]
I have changed some of your original text.

```
RT_Eruption: "Taux d'eruption", 
Eruption_Period: "Période d'éruption", 
Acitve_Period: "Période d'activité", 
Water_Geyser: "Geyser d'eau", 
Polluted_Water_Vent: "Fumerolle d'eau polluée", 
Hydrogen_Vent: "Fumerolle d'hydrogène", 
Polluted_Oxygen_Vent: "Fumerolle d'oxygène pollué", 
Infectious_Polluted_Oxygen_Vent: "Fumerolle d'oxygène pollué infectieux", 
Gold_Volcano: "Volcan d'or", 
to_upload_your_cap: "Pour télécharger votre capture d'écran du geyser.", 
image_too_large: "La taille de l'image est trop grande.", 
```

Is OK?

**Comment by zsnmwy** [comment]
And I'm add French in a temporary web site just now.

https://zsnmwy.coding.me/ONI-PR/

Please use  `Ctrl` + `F5` to refresh the web site.

Please check it.

The web site language will auto jump to your local browser language.

If not 

1.  Delete cookies of the web site
1.  Make sure your local browser language.
1.  Refresh the web site

**Comment by zsnmwy** [comment]
```
Store: ${0}kg/tile, ${1} tiles/cycle
```

Please translate it in French.
I will add a new message in the web site.

Thanks.

**Comment by Neoazureus** [comment]
It's ok

`Dépôt: ${0}kg/bloc, ${1} blocs/cycle`

Edit: i change this line again bloc/cycle > blocs/cycle

**Comment by zsnmwy** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5aee5640c9b0cf0e008c3273/attachments/5af632914f33b71500166f17)

It should be work right now.

Please check the temporary web site.

https://zsnmwy.coding.me/ONI-PR/

Please use `Ctrl` +` F5` to refresh the page.

**Comment by zsnmwy** [comment]
Don't forget to check the translation on the temporary web site.

**Comment by Neoazureus** [comment]
The translation is ok

**Comment by zsnmwy** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5aee5640c9b0cf0e008c3273/attachments/5afaf827c9b0cf0e008eb422)

The web site update is OK.

Please use `Ctrl` + `F5` to refresh the page.
