### ISSUE TITLE
有一个好玩的东西正在产生😆

### ISSUE THREAD

**Issue by mutoe** [zsnmwy/ONI-geyser-calculator#6]
https://game.mutoe.com/oni/

**Comment by mutoe** [comment]
![image](https://user-images.githubusercontent.com/9391981/39692984-158b0374-5215-11e8-8982-2bb9af29ece6.png)

**Comment by zsnmwy** [comment]
```
已拦截跨源请求：同源策略禁止读取位于 https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic?access_token=24.98c6a854b6ab58905121c08481ee9663.2592000.1528279105.282335-11199264 的远程资源。（原因：CORS 头缺少 'Access-Control-Allow-Origin'）。
```
缺了Access-Control-Allow-Origin Headers
跨域问题

---

等我处理那破数据再说，这个识别稍后再弄

**Comment by zsnmwy** [comment]
看了下OCR识别定价，好贵啊

**Comment by mutoe** [comment]
每天500次免费，娱乐娱乐够用了，哪有这么多玩家。。

**Comment by zsnmwy** [comment]
会丢到K社那边的缺氧论坛的 ￣ω￣=

**Comment by mutoe** [comment]
这样的话，可以调集几个网友注册一下百度的开发者帐号，做一个token池，也不是很麻烦
等我明天先接入进来在说

**Comment by mutoe** [comment]
跨域问题确实有，我之前用了插件防跨域没注意，之后把图片上传放到服务器里去就行了，现在在玩家本地上传
也肯能是我没调用对，再看看

**Comment by mutoe** [comment]
现在放到服务器里了，以接口的形式提供出来，目前需要完善的就是泉水种类的判断了。
目前只支持简中，如果要支持其他语言的话还要补充正则条件
接下来我把他植入到页面里来

**Comment by mutoe** [comment]
如果你有服务器的话 可以部署到你的服务器里，需要nodejs环境

**Comment by zsnmwy** [comment]
在翻译上面也会有所不同。  
英文原版，官中，max汉化，还有其他七七八八的翻译。  
服务器，腾讯云之前撸了几年的低配机就有一个。

**Comment by mutoe** [comment]
https://mutoe.github.io/ONI-geyser-calculator/
WOW! 大体可以了，还支持直接ctrl+v粘贴截图了
接下来是英文识别支持

**Comment by zsnmwy** [comment]
nice!! 等你的pr

**Comment by zsnmwy** [comment]
Thanks
