### ISSUE TITLE
这是热泥浆吗，怎么数据有点怪

### ISSUE THREAD

**Issue by mutoe** [zsnmwy/ONI-geyser-calculator#7]
![image](https://user-images.githubusercontent.com/9391981/39694492-140abd6e-521a-11e8-8e45-b7542d7f567a.png)

**Comment by zsnmwy** [comment]
![25e5e0dfbc71e893490c2acf98f4cf3b](https://user-images.githubusercontent.com/35299017/39697490-a8a22f94-5223-11e8-9ade-b6412b73b8ab.png)
![2dc9fc409ad9df0451236f003a9e280e](https://user-images.githubusercontent.com/35299017/39697491-a8d3761c-5223-11e8-908b-5385ef01de4b.png)

---


越牛逼越差，我的妈耶
算法炸了，看看再说

**Comment by zsnmwy** [comment]
原因找到了
这里交换出了问题，不需要交换

```JavaScript
    if (Eruption_Period_Min_Num > Eruption_Period_Max_Num) {
        [Eruption_Period_Min_Num, Eruption_Period_Max_Num] =  [Eruption_Period_Max_Num, Eruption_Period_Min_Num]
    }
    if (Acitve_Period_Min_Num > Acitve_Period_Max_Num) {
        [Acitve_Period_Min_Num, Acitve_Period_Max_Num] =  [Acitve_Period_Max_Num, Acitve_Period_Min_Num]
    }
```
---

注意

"Eruption_Period_Max" 的值

"Eruption_Period_Min" 的值

"Acitve_Period_Max" 的值

"Acitve_Period_Min" 的值

---
## 没有注释前


![](https://ws2.sinaimg.cn/large/006tKfTcgy1fr30adhiroj30w50lkta0.jpg)


---

## 注释后



![](https://ws1.sinaimg.cn/large/006tKfTcgy1fr30azb4hjj30vt0mrwfl.jpg)

**Comment by zsnmwy** [comment]
### 线上的已经更新了

![image](https://user-images.githubusercontent.com/35299017/39700483-f7f7b918-522f-11e8-90a1-0fdac28dce81.png)

**Comment by mutoe** [comment]
我之前改了这里是因为中文和英语语法里面那个周期的大数字和小数字位置不一样，为了交换大小数字才加入的，没想到引发了这个问题

**Comment by mutoe** [comment]
![image](https://user-images.githubusercontent.com/9391981/39755200-79f5d950-52f7-11e8-8284-461842db8738.png)
![image](https://user-images.githubusercontent.com/9391981/39755257-bd702cc6-52f7-11e8-930c-413ce1adaf75.png)

**Comment by zsnmwy** [comment]
你应该把下面四个值打印出来看看

```
"Eruption_Period_Max" 的值

"Eruption_Period_Min" 的值

"Acitve_Period_Max" 的值

"Acitve_Period_Min" 的值
```

~~很有可能是翻转了~~
好像真的bug了，我的天

**Comment by mutoe** [comment]
无视刚才那条。。只是识别的时候多了个0！ 很可能是小数点没有识别出来的原因
不过话说英文环境那个大小值确实应该交换

**Comment by zsnmwy** [comment]
两者不是一样吗？
不需要交换吧
两者的过程值都一样啊

---

![image](https://user-images.githubusercontent.com/35299017/39755567-e7f4813a-52f8-11e8-9331-1c39af3fabec.png)

---

![image](https://user-images.githubusercontent.com/35299017/39755610-181fce8c-52f9-11e8-83e5-0dd5397a2818.png)
